#' 
#' @title Returns a vector of character strings giving the names of the objects on remote server
#' @description this function is similar to R function \code{ls}
#' @details When running analyses one may want to know the objects already generated. This 
#' function is not disclosive as it only returns the names of the objects and not their contents. 
#' As a restriction only objects in the current environment can be displayed and hidden objects 
#' names (names starting with '.') cannot be returned to avoid displaying anything else than
#' the objects generated by the user in the current environment. Unlike the R base version of 
#' this function, the DataSHIELD version does not allow to specify another environment, only 
#' names of objects on the 'current' environment can be displayed.
#' @param datasources a list of \code{\link{DSConnection-class}} objects obtained after login.
#'
#' @return a vector of character strings giving the names of the objects in the 'current' 
#' environment of the remote R session.
#' @author Gaye, A.
#' @export
#' @examples \donttest{
#' 
#'   # load the file that contains the login details
#'   logindata <- DSLite::setupCNSIMTest("dsBase")
#' 
#'   # login and assign the required variables to R
#'   myvar <- list("LAB_TSC")
#'   conns <- datashield.login(logins=logindata,assign=TRUE,variables=myvar)
#' 
#'   # assign 'LAB_TSC' in the dataframe D to a new variable 'labtsc'
#'   ds.assign(toAssign='D$LAB_TSC', newobj='labtsc')
#'
#'   # now call the ds.ls function to display the names of the objects on the server site
#'   ds.ls()
#' 
#'   # clear the Datashield R sessions and logout
#'   datashield.logout(conns)
#' 
#' }
#' 
ds.ls <- function(datasources=NULL){
  
  # look for DS connections
  if(is.null(datasources)){
    datasources <- datashield.connections_find()
  }
  
  # call the server side function that does the job
  cally <- quote("ls()")
  output <- datashield.aggregate(datasources, cally, async = FALSE)
  
  return(output)
}
